[package]
name = "webapps"
version = "0.4.5"
edition = "2021"

[[bin]]
path = "src/main.rs"
name = "cosmic-webapps"

[profile.dev]
opt-level = 1
overflow-checks = false

[dependencies]
anyhow = "1.0.77"
tracing = "0.1"
tracing-subscriber = "0.3.0"
tokio = { version = "1.37.0", features = ["full"] }
reqwest = { version = "0.11.23", features = ["blocking"] }
rand = "0.8.5"
url = "2.5.0"
walkdir = "2.4.0"
dirs = "5.0"
once_cell = "1.19.0"
scraper = "0.18.1"
image = "0.25.1"
usvg = "0.41.0"
lazy_static = "1.4.0"
rust-embed = "8.2.0"
i18n-embed-fl = "0.7.0"
bytes = "1.6.0"
svg = "0.17.0"
base64 = "0.22.1"

[dependencies.i18n-embed]
version = "0.14.1"
features = ["fluent-system", "desktop-requester"]

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
default-features = false
features = ["tokio", "winit"]

[features]
default = ["wgpu"]
wgpu = ["libcosmic/wgpu"]

[dependencies.cosmic-files]
git = "https://github.com/pop-os/cosmic-files.git"
default-features = false
