[package]
name = "webapps"
version = "0.4.8"
edition = "2021"

[[bin]]
path = "src/main.rs"
name = "quick-webapps"

[profile.dev]
opt-level = 1
overflow-checks = false

[dependencies]
anyhow = "1.0.89"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tokio = { version = "1.40.0", features = ["full"] }
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
rand = "0.8.5"
url = "2.5.2"
walkdir = "2.5.0"
dirs = "5.0.1"
once_cell = "1.20.0"
image = "0.25.2"
usvg = "0.43.0"
lazy_static = "1.5.0"
rust-embed = "8.5.0"
i18n-embed-fl = "0.9.1"
bytes = "1.7.1"
svg = "0.17.0"
base64 = "0.22.1"
ashpd = { version = "0.9.1", features = ["wayland"] }

[dependencies.i18n-embed]
version = "0.15.0"
features = ["fluent-system", "desktop-requester"]

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
default-features = false
features = ["tokio", "winit", "wgpu", "dbus-config"]

# [patch.'https://github.com/pop-os/libcosmic']
# libcosmic = { path = "../libcosmic" }
