[package]
name = "wam-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { git = "https://github.com/iced-rs/iced", features = ["tokio", "advanced", "image", "svg"] }
rand = "0.8.5"
reqwest = "0.11.23"
tracing = "0.1"
tracing-subscriber = "0.3.0"
xdg = "2.5.2"
url = "2.5.0"
walkdir = "2.4.0"
